name: ayrnow
description: AYRNOW Phase-2 MVP Scaffold (ALL screens + real UI for core flows)
publish_to: 'none'
version: 1.0.2+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  uuid: ^4.2.2
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/icons/
